  0a[m
  Adding-Damage-From-Weapon[m
  Enemies[m
  Enemy-Sprites[m
  Jack-Nieman[m
  Room-Generation[m
* [32mmain[m
  [31mremotes/origin/Adding-Damage-From-Weapon[m
  [31mremotes/origin/Alex-Knotwell[m
  [31mremotes/origin/Alex-M-Branch[m
  [31mremotes/origin/Ben-Wu[m
  [31mremotes/origin/Domingo-Morales[m
  [31mremotes/origin/Enemies[m
  [31mremotes/origin/Enemies-Scripting[m
  [31mremotes/origin/Enemy-Spawning[m
  [31mremotes/origin/Enemy-Sprites[m
  [31mremotes/origin/Gabriel-Wong[m
  [31mremotes/origin/Generation[m
  [31mremotes/origin/HEAD[m -> origin/main
  [31mremotes/origin/Inventory-UI[m
  [31mremotes/origin/Items[m
  [31mremotes/origin/Jack-Nieman[m
  [31mremotes/origin/Keybinds[m
  [31mremotes/origin/Melee-Weapon[m
  [31mremotes/origin/Player-Animations[m
  [31mremotes/origin/Room-Generation[m
  [31mremotes/origin/Sprite-Rendering[m
  [31mremotes/origin/Story-Features[m
  [31mremotes/origin/Title-Screen[m
  [31mremotes/origin/Weapon-Damage[m
  [31mremotes/origin/Weapon-Equipping[m
  [31mremotes/origin/Weapon-Stat-Randomization[m
  [31mremotes/origin/Weapons-Swapping[m
  [31mremotes/origin/main[m
  [31mremotes/origin/main-test[m
